yarnPath: .yarn/releases/yarn-4.9.2.cjs

nodeLinker: node-modules

# Recommended for Nuxt/JS projects
npmRegistryServer: "https://registry.yarnpkg.com"

# Cache .yarn/cache in CI/CD (Cloudflare Pages, GitHub Actions, etc.)
enableGlobalCache: true
